// twiddle_rom.sv
//
// Generic twiddle ROM for FFT:
//
//   W_N^k = cos(-2πk/N) + j sin(-2πk/N), k = 0..(N/2-1)
//
// Data is stored in Q1.(DATA_W-1) fixed-point, hex, 2's complement.
//
// The ROM is asynchronous-read here (easier for simulation).
// For a true BRAM-based implementation you can make it synchronous
// and add a 1-cycle pipeline.
//
// Files are generated by gen_twiddle_rom.py.

module twiddle_rom #(
    parameter int N          = 512,
    parameter int DATA_W     = 16,
    parameter int ADDR_W     = $clog2(N/2),
    parameter string RE_FILE = "twiddle_re_512_q15.mem",
    parameter string IM_FILE = "twiddle_im_512_q15.mem"
) (
    input  logic [ADDR_W-1:0]        addr,
    output logic signed [DATA_W-1:0] tw_re,
    output logic signed [DATA_W-1:0] tw_im
);

    // Real and imaginary memories
    logic signed [DATA_W-1:0] mem_re [0:(1<<ADDR_W)-1];
    logic signed [DATA_W-1:0] mem_im [0:(1<<ADDR_W)-1];

    initial begin
        $readmemh(RE_FILE, mem_re);
        $readmemh(IM_FILE, mem_im);
    end

    // Async read (combinational)
    assign tw_re = mem_re[addr];
    assign tw_im = mem_im[addr];

endmodule
